### ISSUE TITLE
Front end - Style Navbar component

### ISSUE THREAD

**Issue by frostyshadows** [ubclaunchpad/Internado#145] opened 2019-01-05 22:38 UTC
Style Navbar using this design: https://www.figma.com/file/UzMP6n5OJ7F063dWyxDZe7Zd/Untitled?node-id=34%3A45

*Design not completed yet, update ticket once it's completed*

**Comment by cowmanjoe** [comment] 2019-02-09 22:21
Closing this as I think it is a duplicate of #173

**Closed as completed by cowmanjoe** 2019-02-09 22:21 UTC
